(defun test-map () 
  (list 
    (entry (node "Av. Maipu" "Irigoyen")
           (node "Av. Maipu" "Italia")
           (node "Av. Maipu" "Libertad"))
    (entry (node "Av. Maipu" "Italia")
           (node "Av. Maipu" "Irigoyen")
           (node "Italia" "Lisandro de la Torre"))
    (entry (node "Av. Maipu" "Libertad")
           (node "25 de Mayo" "Libertad"))
    (entry (node "Italia" "Lisandro de la Torre")
           (node "Lisandro de la Torre" "Patricios")
           (node "Italia" "Monasterio"))
    (entry (node "25 de Mayo" "Libertad")
           (node "25 de Mayo" "Irigoyen")
           (node "Libertad" "Lisandro de la Torre"))
    (entry (node "Lisandro de la Torre" "Patricios")
           (node "Lisandro de la Torre" "Irigoyen"))
    (entry (node "Italia" "Monasterio")
           (node "Italia" "Gaspar Campos"))
    (entry (node "25 de Mayo" "Irigoyen")
           (node "Av. Maipu" "Irigoyen"))
    (entry (node "Libertad" "Lisandro de la Torre")
           (node "Libertad" "Monasterio"))
    (entry (node "Lisandro de la Torre" "Irigoyen")
           (node "Lisandro de la Torre" "Libertad")
           (node "Irigoyen" "25 de Mayo"))
    (entry (node "Italia" "Gaspar Campos")
           (node "Gaspar Campos" "Patricios"))
    (entry (node "Libertad" "Monasterio")
           (node "Monasterio" "Irigoyen")
           (node "Libertad" "Gaspar Campos"))
    (entry (node "Gaspar Campos" "Patricios")
           (node "Monasterio" "Patricios")
           (node "Gaspar Campos" "Irigoyen"))
    (entry (node "Monasterio" "Irigoyen")
           (node "Irigoyen" "Lisandro de la Torre")
           (node "Monasterio" "Patricios"))
    (entry (node "Monasterio" "Patricios")
           (node "Monasterio" "Italia")
           (node "Lisandro de la Torre" "Patricios"))
    (entry (node "Gaspar Campos" "Irigoyen")
           (node "Gaspar Campos" "Libertad")
           (node "Irigoyen" "Monasterio"))))
